### ISSUE TITLE
BUG : Graph of On/Off switch not rendering On state

### ISSUE THREAD

**Issue by JRB202** [Dashticz/dashticz#1160]
Code used in CONFIG.js is :

blocks['graph_test'] = {
    devices: [46],
    graph: 'line',
        debugButton: true,
        zoom: true,
    datasetColors: ['red'],
    lineFill: [true],
    legend: true,
}

The cause is :
In graph debug I can see that after 2 On/Off sequences witch values are always read as 0
when On value should be read as 1 

  "data": {
    "result": [
      {
        "d": "2024-02-11 08:30:03",
        "l_46": 0
      },
      {
        "d": "2024-02-11 08:32:04",
        "l_46": 0
      },
      {
        "d": "2024-02-11 09:48:02",
        "l_46": 0
      },
      {
        "d": "2024-02-11 09:53:02",
        "l_46": 0
      }
    ],
    "status": "OK",

**Comment by lokonli** [comment]
Fixed in latest beta with #1163 

Can you test?

**Comment by JRB202** [comment]
Thanks for efforts and update.

Problem is partially fixed only :
Now some values are returned but these value are not the On=1 and Off=0 expected
Value On is rendered with bad value = 101 instead of 1
and
Value Off is rendered with bad value = 1 instead of 0

The test switch is a virtual On/Off 
Type = Light/Switch
Subtype = Switch

**Comment by lokonli** [comment]
Can you post the output of:
http://domoticz/json.htm?param=getlightlog&type=command&idx=15

And also the json device output:
http://domoticz/json.htm?param=getdevices&type=command&rid=15

Instead of 15 use the device you want to show.

**Comment by JRB202** [comment]
Hi,

Here is requested data :

/json.htm?param=getdevices&type=command&rid=46
{
"ActTime" : 1707734536,
"AstrTwilightEnd" : "19:36",
"AstrTwilightStart" : "06:03",
"CivTwilightEnd" : "18:21",
"CivTwilightStart" : "07:18",
"DayLength" : "09:56",
"NautTwilightEnd" : "18:59",
"NautTwilightStart" : "06:40",
"ServerTime" : "2024-02-12 11:42:16",
"SunAtSouth" : "12:50",
"Sunrise" : "07:52",
"Sunset" : "17:48",
"app_version" : "2024.4",
"result" :
[
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 115,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareDisabled" : false,
"HardwareID" : 8,
"HardwareName" : "ActivityMonitor-1",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0001407E",
"Image" : "Motion2",
"IsSubDevice" : false,
"LastUpdate" : "2024-02-12 11:36:03",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "ActivityMonitor-LifeEvent",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" :
[
0
],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "46"
}
],
"status" : "OK",
"title" : "Devices"
}

-------------------------------------------------------------------------------------------------------------------------------------

/json.htm?param=getlightlog&type=command&idx=46

{
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveSelector" : false,
"result" :
[
{
"Data" : "Off",
"Date" : "2024-02-12 11:36:03",
"Level" : 0,
"MaxDimLevel" : 100,
"Status" : "Off",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410868"
},
{
"Data" : "On",
"Date" : "2024-02-12 11:34:03",
"Level" : 0,
"Status" : "On",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410863"
},
{
"Data" : "Off",
"Date" : "2024-02-12 11:34:02",
"Level" : 0,
"Status" : "Off",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410862"
},
{
"Data" : "On",
"Date" : "2024-02-12 11:32:02",
"Level" : 0,
"Status" : "On",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410854"
},
{
"Data" : "Off",
"Date" : "2024-02-12 11:31:02",
"Level" : 0,
"Status" : "Off",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410850"
},
{
"Data" : "On",
"Date" : "2024-02-12 11:29:02",
"Level" : 0,
"Status" : "On",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410843"
},
{
"Data" : "Off",
"Date" : "2024-02-12 11:27:03",
"Level" : 0,
"Status" : "Off",
"User" :
"EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
"idx" : "410838"
},

],
"status" : "OK",
"title" : "getlightlog"
}

**Comment by lokonli** [comment]
And the output of:
http://domoticz/json.htm?param=getlightlog&type=command&idx=46

**Comment by JRB202** [comment]
In the very last Dashticz beta version
the problem is partially fixed only

The value Off is accurate with a 0 value
but 
The On value is 100 instead of 1 

In debug I can see :
      {
        "d": "2024-02-12 18:10:02",
        "l_46": 100
      },
      {
        "d": "2024-02-12 18:14:03",
        "l_46": 0
      }

and 

/json.htm?param=getlightlog&type=command&idx=46

gives :

{
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveSelector" : false,
	"result" : 
	[
		{
			"Data" : "Off",
			"Date" : "2024-02-12 18:14:03",
			"Level" : 0,
			"MaxDimLevel" : 100,
			"Status" : "Off",
			"User" : "EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
			"idx" : "411314"
		},
		{
			"Data" : "On",
			"Date" : "2024-02-12 18:10:02",
			"Level" : 0,
			"Status" : "On",
			"User" : "EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
			"idx" : "411308"
		},
		{
			"Data" : "Off",
			"Date" : "2024-02-12 17:29:03",
			"Level" : 0,
			"Status" : "Off",
			"User" : "EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
			"idx" : "411293"
		},
		{
			"Data" : "On",
			"Date" : "2024-02-12 17:27:03",
			"Level" : 0,
			"Status" : "On",
			"User" : "EventSystem//home/administrator/domoticz/dzVents/runtime/dzVents.lua",
			"idx" : "411289"
		},
	],
	"status" : "OK",
	"title" : "getlightlog"
}

**Comment by lokonli** [comment]
ok, that seems how it was intended to be.

Some switches are a dimmer with dim level between 0 and 100.
Also your switch has maxDimLevel 100

I can add an option to render a switch graph  between two states ('open','close'), or (0, 1), or something else.

**Comment by JRB202** [comment]
Yes Adding an  option to render a switch graph between two states would be useful
